### ISSUE TITLE
タグ機能の実装

### ISSUE THREAD

**Issue by ampcpmgp** [ampcpmgp/am-mocktimes#32]
# 概要
パターンの右横に、タグ機能を入れる
フィルター機能 (https://github.com/ampcpmgp/am-mocktimes/issues/31) 実装後、クリックで絞込、戻るで前の状態に戻る（router機能必須)

![default](https://user-images.githubusercontent.com/13173632/38422576-3bc31726-39e6-11e8-9f2b-d5ec7ac75c2e.png)

# 定義のイメージ

```yaml
pattern 1:
  tags: [2017, bug, special]
pattern 2:
  tags: [2018]
```

※color未指定の場合は、10パターン程度の色を利用。  
１０を超えたら、１パターン目の色に戻る。  

### 案１

配列方式 1
```yaml
tagColors: [2017, #ccc]
```

配列方式 2
```yaml
definition:
  tags: 
    - [#ccc, 2017, 2018, 2019]
    - [#ccc, \d{4}] # 正規表現案
```

### 案２

object方式

```yaml
tags:
  #ccc: [2017, 2018]
```

```yaml
definition:
  tags:
    GROUP_NAME:
      color: #ccc
      items: [2017, 2018]
```

#
