### ISSUE TITLE
afterEachの実装

### ISSUE THREAD

**Issue by ampcpmgp** [ampcpmgp/am-mocktimes#66]
以下のような記述で、関数実行後に共通で追加する処理を記述可能にする。

```yml
patter name:
  func: []
  child pattern name: []
  afterFunc: []
  afterFuncs: - []
```
